### ISSUE TITLE
should not find random inputs in the filter

### ISSUE THREAD

**Issue by imcotton** [kgwinnup/bloom#2] opened 2024-06-02 12:38 UTC
something seems odd here:

```ts
Deno.test("should not find random inputs in the filter", () => {

    const n = 4000;
    const filter = new Bloom(n, 0.0000001);

    const inputs = sample(n);

    for (const item of inputs) {
        filter.insert(item);
    }

    for (const item of inputs) {
        assertEquals(filter.lookup(item), true);
    }

    for (const item of sample(10)) {
        assertEquals(filter.lookup(item), false, "random in filter");
    }

});

function sample(length: number, bytes = 32) {
    return Array.from({ length }, () => {
        return crypto.getRandomValues(new Uint8Array(bytes));
    });
}
```

**Comment by kgwinnup** [comment] 2024-06-02 18:29
Thanks for finding/testing this. I've added this test and confirmed the issue. I suspect it is the hashing algorithm because at least at a quick glance the `buckets(), insert(), lookup()` look okay.

**Comment by imcotton** [comment] 2024-06-02 23:02
https://github.com/kgwinnup/bloom/blob/430b171625f841afea6aef2c254dca5526f78182/bloom.ts#L175-L185

Try this one, bytes to bits:

```ts
const newindex = sum % (this.size * 8);
```

**Comment by kgwinnup** [comment] 2024-06-02 23:36
I pushed the fix, thank you for the help :) 

This issue can be closed.

**Closed as completed** 2024-06-02 23:37 UTC

**Comment by imcotton** [comment] 2024-06-03 00:23
Glad that helped.

btw, I saw you had also changed the `Murmur3.hash32` function slightly, does it affects to this issue?\
Or just passing by cleanups.

**Comment by imcotton** [comment] 2024-06-04 17:16
@kgwinnup /ping

**Comment by kgwinnup** [comment] 2024-06-04 18:01
Unrelated, these are just cleanup. I think at some point I need to add some
tests for this.

**Comment by imcotton** [comment] 2024-06-04 18:25
Got it, I mimicked the change in order to keep the consistency anyway, just to make sure here.
